services:
  - type: web
    name: nutrisnap-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false # Set manually in Render dashboard
      - key: MONGODB_URI
        sync: false # Set manually in Render dashboard
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false # Set manually in Render dashboard
